In [1]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

In [2]:
#导入文件利用路径变量导入，分为相对引用和绝对引用
path = "Chipotle_datas.tsv"
df = pd.read_csv(path, sep = "\t")
#利用pd.read_csv转化为DataFrame，参数中写入路径和分隔符（默认用逗号）
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [3]:
#查看数据集的结构：shape,columns,info

In [4]:
#查看前十行数据：.head  后十行：.tail
df.head(6)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98

In [5]:
df.tail(7)

,order_id,quantity,item_name,choice_description,item_price
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75
4616,1832,1,Chips and Guacamole,NaN,$4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [9]:
#统计数据集中某一列中每一个数据重复出现的次数：.value_counts()   （得到一个series）
df['item_name'].value_counts(ascending = True)

item_name
Carnitas Salad                             1
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Bowl                                       2
Salad                                      2
Crispy Tacos                               2
Steak Salad                                4
Burrito                                    6
Veggie Salad                               6
Carnitas Salad Bowl                        6
Veggie Soft Tacos                          7
Carnitas Crispy Tacos                      7
Chicken Salad                              9
Barbacoa Salad Bowl                       10
Barbacoa Crispy Tacos                     11
Chips and Roasted Chili-Corn Salsa        18
Veggie Salad Bowl                         18
Izze                                      20
Chips and Tomatillo-Red Chili Salsa       20
Chips and Roasted Chili Corn Salsa        22
Barbacoa Soft Tacos                       25
Nantucket Nectar                          27
Steak Salad Bowl                          29
Chips and Tomatillo-Green Chili Salsa     31
Steak Crispy Tacos                        35
Carnitas Soft Tacos                       40
Chips and Tomatillo Green Chili Salsa     43
Chicken Crispy Tacos                      47
Chips and Tomatillo Red Chili Salsa       48
6 Pack Soft Drink                         54
Steak Soft Tacos                          55
Carnitas Burrito                          59
Barbacoa Bowl                             66
Carnitas Bowl                             68
Veggie Bowl                               85
Barbacoa Burrito                          91
Veggie Burrito                            95
Side of Chips                            101
Canned Soda                              104
Chicken Salad Bowl                       110
Chips and Fresh Tomato Salsa             110
Chicken Soft Tacos                       115
Bottled Water                            162
Steak Bowl                               211
Chips                                    211
Canned Soft Drink                        301
Steak Burrito                            368
Chips and Guacamole                      479
Chicken Burrito                          553
Chicken Bowl                             726
Name: count, dtype: int64

In [10]:
#统计数据集中出现数据的种类
df['item_name'].value_counts(ascending = True).shape

(50,)

In [12]:
#还可以用.nunique
df['item_name'].nunique()

50

In [16]:
#统计choice_description中出现最多的选项
df['choice_description'].value_counts().head(1)

choice_description
[Diet Coke]    134
Name: count, dtype: int64

In [19]:
df['quantity'].sum()

np.int64(4972)

In [22]:
#对某一列进行算法的操作与处理: .apply() 参数为函数或者lambda表达式
df['item_price'].apply(lambda x: float(x[1:]))

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
        ...
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

In [24]:
#创建新的一列，直接写新索引然后赋值
df['item_price_float'] = df['item_price'].apply(lambda x: float(x[1:]))
df.head()

,order_id,quantity,item_name,choice_description,item_price,item_price_float
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39
1,1,1,Izze,[Clementine],$3.39,3.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98

In [31]:
#计算共有多少单订单
df.order_id.nunique()

1834

In [32]:
df.order_id.value_counts().count()

np.int64(1834)

In [35]:
df.order_id.value_counts().shape

(1834,)

In [49]:
#分别计算每一单的总价，然后求均值（分组求和+求均值）
#分组函数：.groupby()
#求平均值函数：.mean()[]
df.groupby(['order_id']).sum()['item_price_float'].mean()

np.float64(18.811428571428568)