In [1]:
#2012欧洲杯数据分析
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

In [2]:
path = 'Euro_2012_stats_TEAM.csv'
foot = pd.read_csv(path)
foot

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.90%,16.00%,32,0,0,0,...,13,81.30%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.90%,12.90%,39,0,0,0,...,9,60.10%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.00%,20.00%,27,1,0,0,...,10,66.70%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.00%,17.20%,40,0,0,0,...,22,88.10%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.90%,6.50%,65,1,0,0,...,6,54.60%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.80%,15.60%,80,2,1,0,...,10,62.60%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.70%,19.20%,32,1,1,1,...,13,65.10%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.00%,7.50%,110,2,0,0,...,20,74.10%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.00%,4.10%,60,2,0,0,...,12,70.60%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.40%,5.20%,48,0,0,0,...,6,66.70%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.30%,9.30%,82,6,0,0,...,10,71.50%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.80%,5.20%,28,0,0,0,...,17,65.40%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.50%,12.50%,59,2,0,0,...,10,77.00%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.90%,16.00%,100,0,1,0,...,15,93.80%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.20%,13.80%,39,3,0,0,...,8,61.60%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.20%,6.00%,38,0,0,0,...,13,76.50%,48,31,4,5,0,9,9,18

In [4]:
#结构 列信息
foot.shape

(16, 35)

In [5]:
foot.columns

Index(['Team', 'Goals', 'Shots on target', 'Shots off target',
       'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)',
       'Hit Woodwork', 'Penalty goals', 'Penalties not scored', 'Headed goals',
       'Passes', 'Passes completed', 'Passing Accuracy', 'Touches', 'Crosses',
       'Dribbles', 'Corners Taken', 'Tackles', 'Clearances', 'Interceptions',
       'Clearances off line', 'Clean Sheets', 'Blocks', 'Goals conceded',
       'Saves made', 'Saves-to-shots ratio', 'Fouls Won', 'Fouls Conceded',
       'Offsides', 'Yellow Cards', 'Red Cards', 'Subs on', 'Subs off',
       'Players Used'],
      dtype='object')

In [6]:
foot.info

<bound method DataFrame.info of                    Team  Goals  Shots on target  Shots off target  \
0               Croatia      4               13                12
1        Czech Republic      4               13                18
2               Denmark      4               10                10
3               England      5               11                18
4                France      3               22                24
5               Germany     10               32                32
6                Greece      5                8                18
7                 Italy      6               34                45
8           Netherlands      2               12                36
9                Poland      2               15                23
10             Portugal      6               22                42
11  Republic of Ireland      1                7                12
12               Russia      5                9                31
13                Spain     12               42                33
14               Sweden      5               17                19
15              Ukraine      2                7                26

   Shooting Accuracy % Goals-to-shots  Total shots (inc. Blocked)  \
0             51.90%           16.00%                          32
1             41.90%           12.90%                          39
2             50.00%           20.00%                          27
3             50.00%           17.20%                          40
4             37.90%            6.50%                          65
5             47.80%           15.60%                          80
6             30.70%           19.20%                          32
7             43.00%            7.50%                         110
8             25.00%            4.10%                          60
9             39.40%            5.20%                          48
10            34.30%            9.30%                          82
11            36.80%            5.20%                          28
12            22.50%           12.50%                          59
13            55.90%           16.00%                         100
14            47.20%           13.80%                          39
15            21.20%            6.00%                          38

    Hit Woodwork  Penalty goals  Penalties not scored  ...  Saves made  \
0              0              0                     0  ...          13
1              0              0                     0  ...           9
2              1              0                     0  ...          10
3              0              0                     0  ...          22
4              1              0                     0  ...           6
5              2              1                     0  ...          10
6              1              1                     1  ...          13
7              2              0                     0  ...          20
8              2              0                     0  ...          12
9              0              0                     0  ...           6
10             6              0                     0  ...          10
11             0              0                     0  ...          17
12             2              0                     0  ...          10
13             0              1                     0  ...          15
14             3              0                     0  ...           8
15             0              0                     0  ...          13

    Saves-to-shots ratio  Fouls Won Fouls Conceded  Offsides  Yellow Cards  \
0                 81.30%         41             62         2             9
1                 60.10%         53             73         8             7
2                 66.70%         25             38         8             4
3                 88.10%         43             45         6             5
4                 54.60%         36             51         5             6
5                 62.60%         63             49        12             4
6                 65.10%         67             48        12             9
7                 74.10%        101             89        16            16
8                 70.60%         35             30         3             5
9                 66.70%         48             56         3             7
10                71.50%         73             90        10            12
11                65.40%         43             51        11             6
12                77.00%         34             43         4             6
13                93.80%        102             83        19            11
14                61.60%         35             51         7             7
15                76.50%         48             31         4             5

    Red Cards  Subs on  Subs off  Players Used
0           0        9         9            16
1           0       11        11            19
2           0        7         7            15
3           0       11        11            16
4           0       11        11            19
5           0       15        15            17
6           1       12        12            20
7           0       18        18            19
8           0        7         7            15
9           1        7         7            17
10          0       14        14            16
11          1       10        10            17
12          0        7         7            16
13          0       17        17            18
14          0        9         9            18
15          0        9         9            18

[16 rows x 35 columns]>

In [7]:
#求总进球数
foot.Goals.sum()

np.int64(76)

In [8]:
#求队伍总数
foot.Team.count()

np.int64(16)

In [9]:
foot.shape[0]

16

In [11]:
#创建一个新的数据集，单独存放每个队伍的黄牌与红牌
cards = foot[['Team','Yellow Cards','Red Cards']]
cards

                   Team  Yellow Cards  Red Cards
0               Croatia             9          0
1        Czech Republic             7          0
2               Denmark             4          0
3               England             5          0
4                France             6          0
5               Germany             4          0
6                Greece             9          1
7                 Italy            16          0
8           Netherlands             5          0
9                Poland             7          1
10             Portugal            12          0
11  Republic of Ireland             6          1
12               Russia             6          0
13                Spain            11          0
14               Sweden             7          0
15              Ukraine             5          0

In [12]:
#不同优先级排序
cards.sort_values(['Yellow Cards','Red Cards'],ascending = False)

                   Team  Yellow Cards  Red Cards
7                 Italy            16          0
10             Portugal            12          0
13                Spain            11          0
6                Greece             9          1
0               Croatia             9          0
9                Poland             7          1
1        Czech Republic             7          0
14               Sweden             7          0
11  Republic of Ireland             6          1
4                France             6          0
12               Russia             6          0
3               England             5          0
8           Netherlands             5          0
15              Ukraine             5          0
2               Denmark             4          0
5               Germany             4          0

In [15]:
#计算每一只球队黄牌的平均值
cards['Yellow Cards'].mean()

np.float64(7.4375)

In [17]:
#求进球数大于6的球队
foot[foot.Goals > 6]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
5,Germany,10,32,32,47.80%,15.60%,80,2,1,0,...,10,62.60%,63,49,12,4,0,15,15,17
13,Spain,12,42,33,55.90%,16.00%,100,0,1,0,...,15,93.80%,102,83,19,11,0,17,17,18

In [19]:
#选取数据集中的前七列，iloc切片
foot.iloc[3:7,0:7]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked)
3,England,5,11,18,50.00%,17.20%,40
4,France,3,22,24,37.90%,6.50%,65
5,Germany,10,32,32,47.80%,15.60%,80
6,Greece,5,8,18,30.70%,19.20%,32

In [26]:
foot.loc[[3,6,9,12],['Team','Shots on target']]

       Team  Shots on target
3   England               11
6    Greece                8
9    Poland               15
12   Russia                9

In [27]:
#选取除了后三列之外的全部数据
foot.iloc[3:7,0:-3]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Clean Sheets,Blocks,Goals conceded,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards
3,England,5,11,18,50.00%,17.20%,40,0,0,0,...,2,29,3,22,88.10%,43,45,6,5,0
4,France,3,22,24,37.90%,6.50%,65,1,0,0,...,1,7,5,6,54.60%,36,51,5,6,0
5,Germany,10,32,32,47.80%,15.60%,80,2,1,0,...,1,11,6,10,62.60%,63,49,12,4,0
6,Greece,5,8,18,30.70%,19.20%,32,1,1,1,...,1,23,7,13,65.10%,67,48,12,9,1

In [34]:
#查看英格兰，法国，德国的射正率
foot[foot.Team.isin(['England','France','Germany'])][['Team','Shooting Accuracy']]

      Team Shooting Accuracy
3  England            50.00%
4   France            37.90%
5  Germany            47.80%

In [35]:
foot.loc[foot.Team.isin(['England','France','Germany'])][['Team','Shooting Accuracy']]

      Team Shooting Accuracy
3  England            50.00%
4   France            37.90%
5  Germany            47.80%