In [1]:
#二手房数据分析
import numpy as np
import pandas as pd
from pandas import DataFrame,Series

In [30]:
path = 'fangzi.csv'
data = pd.read_csv(path)
data

C:\Users\ZPth\AppData\Local\Temp\ipykernel_22500\2148845746.py:2: DtypeWarning: Columns (1,11,12,13,14,27) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(path)

,URL,ID,Lng,Lat,CommunityID,TradeTime,DOM,Followers,Total price,Price,...,building structure,Ladder ratio(梯户比),Elevator,Property rights for five years（房屋满五年）,Subway,District,Community average,Unnamed: 26,Unnamed: 27,Unnamed: 28
0,https://bj.lianjia.com/chengjiao/101084782030....,101084782030.0,116.475489,40.019520,1111027376244,2016/8/9,1464.0,106,415.0,31680,...,钢混,0.217,1.0,0.0,1.0,朝阳,56021.0,NaN,NaN,NaN
1,https://bj.lianjia.com/chengjiao/101086012217....,101086012217.0,116.453917,39.881534,1111027381879,2016/7/28,903.0,126,575.0,43436,...,钢混,0.667,1.0,1.0,0.0,朝阳,71539.0,NaN,NaN,NaN
2,https://bj.lianjia.com/chengjiao/101086041636....,101086041636.0,116.561978,39.877145,1111040862969,2016/12/11,1271.0,48,1030.0,52021,...,钢混,0.500,1.0,0.0,0.0,朝阳,48160.0,NaN,NaN,NaN
3,https://bj.lianjia.com/chengjiao/101086406841....,101086406841.0,116.438010,40.076114,1111043185817,2016/9/30,965.0,138,297.5,22202,...,钢混,0.273,1.0,0.0,0.0,昌平,51238.0,NaN,NaN,NaN
4,https://bj.lianjia.com/chengjiao/101086920653....,101086920653.0,116.428392,39.886229,1111027381174,2016/8/28,927.0,286,392.0,48396,...,混合,0.333,0.0,1.0,1.0,东城,62588.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318846,https://bj.lianjia.com/chengjiao/BJYZ92311192....,BJYZ92311192,116.546899,39.755236,1111027377053,2016/6/10,1.0,8,350.0,20580,...,钢混,0.333,0.0,1.0,0.0,亦庄开发区,36545.0,NaN,NaN,NaN
318847,https://bj.lianjia.com/chengjiao/BJYZ92320171....,BJYZ92320171,116.497474,39.810115,1111027377957,2016/6/10,NaN,1,108.8,31006,...,钢混,0.222,1.0,0.0,1.0,亦庄开发区,54282.0,NaN,NaN,NaN
318848,https://bj.lianjia.com/chengjiao/BJYZ92324217....,BJYZ92324217,116.497256,39.804081,1111027380056,2016/6/5,1.0,2,359.0,35138,...,钢混,0.500,1.0,1.0,0.0,亦庄开发区,46927.0,NaN,NaN,NaN
318849,https://bj.lianjia.com/chengjiao/BJYZ92333313....,BJYZ92333313,116.501794,39.799347,1111027377054,2016/6/12,NaN,4,720.0,40373,...,混合,0.500,0.0,1.0,0.0,亦庄开发区,54842.0,NaN,NaN,NaN
318850,https://bj.lianjia.com/chengjiao/BJYZ92363553....,BJYZ92363553,116.497474,39.810115,1111027377957,2016/6/11,1.0,0,450.0,48675,...,钢混,1.000,1.0,0.0,1.0,亦庄开发区,54282.0,NaN,NaN,NaN

In [3]:
data.shape

(318851, 29)

In [4]:
data.columns

Index(['URL', 'ID', 'Lng', 'Lat', 'CommunityID', 'TradeTime', 'DOM',
       'Followers', 'Total price', 'Price', 'Square', 'Bed Room',
       'Living room', 'Kitchen', 'Bathroom', '楼', 'Building Type',
       'Construction time', 'renovation condition', 'building structure',
       'Ladder ratio(梯户比)', 'Elevator',
       'Property rights for five years（房屋满五年）', 'Subway', 'District',
       'Community average', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28'],
      dtype='object')

In [5]:
#建造最早的房子的成交价格
#先查看数据集中是否含有脏数据
s = data['Construction time']
s

0         2005
1         2004
2         2005
3         2008
4         1960
          ...
318846    2003
318847    2009
318848    2000
318849    2003
318850      未知
Name: Construction time, Length: 318851, dtype: object

In [13]:
s_num = pd.to_numeric(s,errors = 'coerce')
s_num

0         2005.0
1         2004.0
2         2005.0
3         2008.0
4         1960.0
           ...
318846    2003.0
318847    2009.0
318848    2000.0
318849    2003.0
318850       NaN
Name: Construction time, Length: 318851, dtype: float64

In [14]:
s_num[s_num < 1000].value_counts()

Construction time
1.0    16
0.0    16
Name: count, dtype: int64

In [21]:
index1 = s_num[s_num.isnull()].index
index2 = s_num[(s_num == 0)|(s_num == 1)].index
index2

Index([ 92235,  92251,  92267,  92270,  92297,  92299,  92300,  92304,  92340,
        92349,  92356,  92398,  92409,  92414,  92467,  92520,  92610,  92660,
        92814,  92845,  92899, 113275, 141376, 208214, 220567, 220569, 220570,
       220603, 224349, 243731, 244054, 245394],
      dtype='int64')

In [31]:
#根据索引删除数据集中的数据：.drop(index,inplace = )
data.drop(index1, inplace = True)
data

,URL,ID,Lng,Lat,CommunityID,TradeTime,DOM,Followers,Total price,Price,...,building structure,Ladder ratio(梯户比),Elevator,Property rights for five years（房屋满五年）,Subway,District,Community average,Unnamed: 26,Unnamed: 27,Unnamed: 28
0,https://bj.lianjia.com/chengjiao/101084782030....,101084782030.0,116.475489,40.019520,1111027376244,2016/8/9,1464.0,106,415.0,31680,...,钢混,0.217,1.0,0.0,1.0,朝阳,56021.0,NaN,NaN,NaN
1,https://bj.lianjia.com/chengjiao/101086012217....,101086012217.0,116.453917,39.881534,1111027381879,2016/7/28,903.0,126,575.0,43436,...,钢混,0.667,1.0,1.0,0.0,朝阳,71539.0,NaN,NaN,NaN
2,https://bj.lianjia.com/chengjiao/101086041636....,101086041636.0,116.561978,39.877145,1111040862969,2016/12/11,1271.0,48,1030.0,52021,...,钢混,0.500,1.0,0.0,0.0,朝阳,48160.0,NaN,NaN,NaN
3,https://bj.lianjia.com/chengjiao/101086406841....,101086406841.0,116.438010,40.076114,1111043185817,2016/9/30,965.0,138,297.5,22202,...,钢混,0.273,1.0,0.0,0.0,昌平,51238.0,NaN,NaN,NaN
4,https://bj.lianjia.com/chengjiao/101086920653....,101086920653.0,116.428392,39.886229,1111027381174,2016/8/28,927.0,286,392.0,48396,...,混合,0.333,0.0,1.0,1.0,东城,62588.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318845,https://bj.lianjia.com/chengjiao/BJYZ92303482....,BJYZ92303482,116.546899,39.755236,1111027377053,2016/6/9,1.0,8,355.5,26491,...,钢混,0.500,1.0,1.0,0.0,亦庄开发区,36545.0,NaN,NaN,NaN
318846,https://bj.lianjia.com/chengjiao/BJYZ92311192....,BJYZ92311192,116.546899,39.755236,1111027377053,2016/6/10,1.0,8,350.0,20580,...,钢混,0.333,0.0,1.0,0.0,亦庄开发区,36545.0,NaN,NaN,NaN
318847,https://bj.lianjia.com/chengjiao/BJYZ92320171....,BJYZ92320171,116.497474,39.810115,1111027377957,2016/6/10,NaN,1,108.8,31006,...,钢混,0.222,1.0,0.0,1.0,亦庄开发区,54282.0,NaN,NaN,NaN
318848,https://bj.lianjia.com/chengjiao/BJYZ92324217....,BJYZ92324217,116.497256,39.804081,1111027380056,2016/6/5,1.0,2,359.0,35138,...,钢混,0.500,1.0,1.0,0.0,亦庄开发区,46927.0,NaN,NaN,NaN
318849,https://bj.lianjia.com/chengjiao/BJYZ92333313....,BJYZ92333313,116.501794,39.799347,1111027377054,2016/6/12,NaN,4,720.0,40373,...,混合,0.500,0.0,1.0,0.0,亦庄开发区,54842.0,NaN,NaN,NaN

In [32]:
data.drop(index2, inplace = True)
data

,URL,ID,Lng,Lat,CommunityID,TradeTime,DOM,Followers,Total price,Price,...,building structure,Ladder ratio(梯户比),Elevator,Property rights for five years（房屋满五年）,Subway,District,Community average,Unnamed: 26,Unnamed: 27,Unnamed: 28
0,https://bj.lianjia.com/chengjiao/101084782030....,101084782030.0,116.475489,40.019520,1111027376244,2016/8/9,1464.0,106,415.0,31680,...,钢混,0.217,1.0,0.0,1.0,朝阳,56021.0,NaN,NaN,NaN
1,https://bj.lianjia.com/chengjiao/101086012217....,101086012217.0,116.453917,39.881534,1111027381879,2016/7/28,903.0,126,575.0,43436,...,钢混,0.667,1.0,1.0,0.0,朝阳,71539.0,NaN,NaN,NaN
2,https://bj.lianjia.com/chengjiao/101086041636....,101086041636.0,116.561978,39.877145,1111040862969,2016/12/11,1271.0,48,1030.0,52021,...,钢混,0.500,1.0,0.0,0.0,朝阳,48160.0,NaN,NaN,NaN
3,https://bj.lianjia.com/chengjiao/101086406841....,101086406841.0,116.438010,40.076114,1111043185817,2016/9/30,965.0,138,297.5,22202,...,钢混,0.273,1.0,0.0,0.0,昌平,51238.0,NaN,NaN,NaN
4,https://bj.lianjia.com/chengjiao/101086920653....,101086920653.0,116.428392,39.886229,1111027381174,2016/8/28,927.0,286,392.0,48396,...,混合,0.333,0.0,1.0,1.0,东城,62588.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318845,https://bj.lianjia.com/chengjiao/BJYZ92303482....,BJYZ92303482,116.546899,39.755236,1111027377053,2016/6/9,1.0,8,355.5,26491,...,钢混,0.500,1.0,1.0,0.0,亦庄开发区,36545.0,NaN,NaN,NaN
318846,https://bj.lianjia.com/chengjiao/BJYZ92311192....,BJYZ92311192,116.546899,39.755236,1111027377053,2016/6/10,1.0,8,350.0,20580,...,钢混,0.333,0.0,1.0,0.0,亦庄开发区,36545.0,NaN,NaN,NaN
318847,https://bj.lianjia.com/chengjiao/BJYZ92320171....,BJYZ92320171,116.497474,39.810115,1111027377957,2016/6/10,NaN,1,108.8,31006,...,钢混,0.222,1.0,0.0,1.0,亦庄开发区,54282.0,NaN,NaN,NaN
318848,https://bj.lianjia.com/chengjiao/BJYZ92324217....,BJYZ92324217,116.497256,39.804081,1111027380056,2016/6/5,1.0,2,359.0,35138,...,钢混,0.500,1.0,1.0,0.0,亦庄开发区,46927.0,NaN,NaN,NaN
318849,https://bj.lianjia.com/chengjiao/BJYZ92333313....,BJYZ92333313,116.501794,39.799347,1111027377054,2016/6/12,NaN,4,720.0,40373,...,混合,0.500,0.0,1.0,0.0,亦庄开发区,54842.0,NaN,NaN,NaN

In [34]:
#检查脏数据是否被删除
data['Construction time'].value_counts()

Construction time
2004    21145
2003    19409
2005    18924
2006    14854
2007    14213
        ...
1944        2
1934        2
1933        1
1906        1
1914        1
Name: count, Length: 71, dtype: int64

In [47]:
data.sort_values(['Construction time','Total price'])[['Construction time','Total price']]

       Construction time  Total price
298468              1906        950.0
317054              1914        214.0
89155               1933        164.3
314037              1934        173.5
315321              1934        245.0
...                  ...          ...
79656               2016       1220.0
32757               2016       1330.0
28950               2016       1430.0
62880               2016       1860.0
65060               2016       2330.0

[299536 rows x 2 columns]

In [53]:
#哪个区域卖出的房子最多？
data.groupby(['District']).count()['URL']

District
东城        15979
丰台        27904
亦庄开发区      2300
大兴        14603
房山         2859
昌平        36244
朝阳       101554
海淀        35567
石景山       10459
西城        29319
通州        12140
门头沟        1619
顺义         8989
Name: URL, dtype: int64

In [54]:
#不分组做法
data.District.value_counts()

District
朝阳       101554
昌平        36244
海淀        35567
西城        29319
丰台        27904
东城        15979
大兴        14603
通州        12140
石景山       10459
顺义         8989
房山         2859
亦庄开发区      2300
门头沟        1619
Name: count, dtype: int64

In [59]:
#哪个区的房子平均价格最高
data.groupby(['District'])['Total price'].mean().sort_values(ascending = False)

District
西城       450.873505
东城       440.838307
海淀       431.904718
朝阳       368.720977
亦庄开发区    303.520261
丰台       300.316087
昌平       284.181197
石景山      268.349049
大兴       259.737054
房山       250.742357
通州       235.361540
门头沟      223.470784
顺义       223.247669
Name: Total price, dtype: float64

In [61]:
#海淀区的平均房价(每平米)
data[data['District']=='海淀']['Price'].mean()

np.float64(55214.45938650997)

In [65]:
#西城区的房子中有多少两居室
data[(data.District=='西城') & (data['Bed Room']==2)].count()

URL                                      12874
ID                                       12874
Lng                                      12874
Lat                                      12874
CommunityID                              12874
TradeTime                                12874
DOM                                       5912
Followers                                12874
Total price                              12874
Price                                    12874
Square                                   12874
Bed Room                                 12874
Living room                              12874
Kitchen                                  12874
Bathroom                                 12874
楼                                        12874
Building Type                            12870
Construction time                        12874
renovation condition                     12874
building structure                       12874
Ladder ratio(梯户比)                        12874
Elevator                                 12874
Property rights for five years（房屋满五年）    12874
Subway                                   12874
District                                 12874
Community average                        12832
Unnamed: 26                                  0
Unnamed: 27                               8565
Unnamed: 28                               8564
dtype: int64