In [1]:
#王者荣耀数据分析
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

In [2]:
path = 'type_hero.csv'
hero = pd.read_csv(path)
hero

,英雄类型,英雄名称,最大生命,最大法力,物理攻击,法术攻击,物理防御,物理减伤率,法术防御,法术减伤率,...,攻速加成,暴击几率,暴击效果,物理吸血,法术吸血,冷却缩减,攻击范围,韧性,生命回复,法力回复
0,坦克,苏烈,3369,0,171,0,93,13.4%,50,7.6%,...,0,0,200%,0,0,0%,近程,0,56,0
1,坦克,芈月,3105,100,152,0,88,12.7%,50,7.6%,...,0,0,200%,0,0,0%,远程,0,44,0
2,坦克,墨子,3083,420,181,0,102,14.5%,50,7.6%,...,0,0,200%,0,0,0%,近程,0,51,15
3,坦克,白起,3510,420,158,0,120,16.6%,50,7.6%,...,0,0,200%,0,0,0%,近程,0,58,14
4,坦克,庄周,3311,420,170,0,150,20%,50,7.6%,...,0,0,200%,0,0,0%,近程,0,55,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,射手,艾琳,3182,440,161,0,86,12.5%,50,7.6%,...,0,0,200%,0,0,0%,远程,0,41,16
67,坦克,太乙真人,3443,420,154,0,94,13.5%,50,0%,...,0,0,0%,0,0,0%,近程,0,49,15
68,辅助,大乔,2958,470,159,0,93,13.4%,50,7.6%,...,0,0,200%,0,0,0%,远程,0,42,17
69,法师,孙膑,3208,470,176,0,98,14.1%,50,7.6%,...,0,0,200%,0,0,0%,远程,0,45,17
70,辅助,蔡文姬,3238,470,159,0,96,13.7%,50,7.6%,...,0,0,200%,0,0,0%,远程,0,38,17

In [3]:
hero.columns

Index(['英雄类型', '英雄名称', '最大生命', '最大法力', '物理攻击', '法术攻击', '物理防御', '物理减伤率', '法术防御',
       '法术减伤率', '物理护甲穿透', '法术护甲穿透', '攻速加成', '暴击几率', '暴击效果', '物理吸血', '法术吸血',
       '冷却缩减', '攻击范围', '韧性', '生命回复', '法力回复'],
      dtype='object')

In [4]:
hero.shape

(71, 22)

In [5]:
#寻找单列中的最大值（排序）：.sort_values(by=[''])
hero.sort_values(by = ['最大生命'],ascending = False)

,英雄类型,英雄名称,最大生命,最大法力,物理攻击,法术攻击,物理防御,物理减伤率,法术防御,法术减伤率,...,攻速加成,暴击几率,暴击效果,物理吸血,法术吸血,冷却缩减,攻击范围,韧性,生命回复,法力回复
9,坦克,亚瑟,3622,0,164,0,98,14.1%,50,7.6%,...,0,0,200%,0,0,0%,近程,0,55,0
7,坦克,吕布,3564,0,170,0,99,14.1%,50,7.6%,...,0,0,200%,0,0,0%,近程,0,54,0
5,坦克,廉颇,3558,420,163,0,132,18%,50,7.6%,...,0,0,200%,0,0,0%,近程,0,59,15
8,坦克,牛魔,3537,470,156,0,109,15.3%,50,7.6%,...,0,0,200%,0,0,0%,近程,0,58,17
15,坦克,项羽,3535,420,157,0,123,17%,50,7.6%,...,0,0,200%,0,0,0%,近程,0,55,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,法师,姜子牙,2958,490,168,0,106,15%,50,7.6%,...,0,0,200%,0,0,0%,远程,0,42,18
33,战士,宫本武藏,2902,0,157,0,106,15%,50,7.6%,...,0,0,200%,0,0,0%,近程,0,47,0
25,战士,花木兰,2886,0,170,0,86,12.5%,50,7.6%,...,0,0,200%,0,0,0%,近程,0,44,0
11,坦克,雅典娜,2862,430,162,0,106,15%,50,7.6%,...,0,0,200%,0,0,0%,近程,0,44,15
46,法师,武则天,2860,490,173,0,95,13.6%,50,7.6%,...,0,0,200%,0,0,0%,远程,0,40,18

In [6]:
#查看分组后的平均值 注:求平均值若只对数字类型求，需在参数中添加numeric_only = True
#查看不同位置的英雄的数值平均值

In [7]:
h = hero.groupby(by = ['英雄类型']).mean(numeric_only = True)
h.sort_values(['物理防御'],ascending = False)

,最大生命,最大法力,物理攻击,法术攻击,物理防御,法术防御,物理护甲穿透,法术护甲穿透,生命回复,法力回复
英雄类型,,,,,,,,,,
坦克,3353.909091,307.727273,163.590909,0.0,109.227273,50.0,0.0,0.0,53.454545,11.000000
战士,3195.866667,318.666667,167.400000,0.0,95.666667,50.0,0.0,0.0,49.000000,11.333333
辅助,3098.000000,470.000000,159.000000,0.0,94.500000,50.0,0.0,0.0,40.000000,17.000000
法师,3102.750000,487.500000,164.500000,0.0,91.437500,50.0,0.0,0.0,43.875000,17.500000
射手,3140.700000,416.000000,168.600000,0.0,88.200000,50.0,0.0,0.0,40.000000,19.000000
刺客,3235.500000,340.000000,172.666667,0.0,87.333333,50.0,0.0,0.0,48.166667,19.666667

In [8]:
#对所有列进行函数运算：.applymap?即将废弃
#保留三位小数
h.round(3)

,最大生命,最大法力,物理攻击,法术攻击,物理防御,法术防御,物理护甲穿透,法术护甲穿透,生命回复,法力回复
英雄类型,,,,,,,,,,
刺客,3235.500,340.000,172.667,0.0,87.333,50.0,0.0,0.0,48.167,19.667
坦克,3353.909,307.727,163.591,0.0,109.227,50.0,0.0,0.0,53.455,11.000
射手,3140.700,416.000,168.600,0.0,88.200,50.0,0.0,0.0,40.000,19.000
战士,3195.867,318.667,167.400,0.0,95.667,50.0,0.0,0.0,49.000,11.333
法师,3102.750,487.500,164.500,0.0,91.438,50.0,0.0,0.0,43.875,17.500
辅助,3098.000,470.000,159.000,0.0,94.500,50.0,0.0,0.0,40.000,17.000

In [9]:
h*2+6

,最大生命,最大法力,物理攻击,法术攻击,物理防御,法术防御,物理护甲穿透,法术护甲穿透,生命回复,法力回复
英雄类型,,,,,,,,,,
刺客,6477.000000,686.000000,351.333333,6.0,180.666667,106.0,6.0,6.0,102.333333,45.333333
坦克,6713.818182,621.454545,333.181818,6.0,224.454545,106.0,6.0,6.0,112.909091,28.000000
射手,6287.400000,838.000000,343.200000,6.0,182.400000,106.0,6.0,6.0,86.000000,44.000000
战士,6397.733333,643.333333,340.800000,6.0,197.333333,106.0,6.0,6.0,104.000000,28.666667
法师,6211.500000,981.000000,335.000000,6.0,188.875000,106.0,6.0,6.0,93.750000,41.000000
辅助,6202.000000,946.000000,324.000000,6.0,195.000000,106.0,6.0,6.0,86.000000,40.000000

In [10]:
#遍历进行批量操作:apply和map结合使用
h.apply(lambda col: col.map(lambda x: round(x,3)))

,最大生命,最大法力,物理攻击,法术攻击,物理防御,法术防御,物理护甲穿透,法术护甲穿透,生命回复,法力回复
英雄类型,,,,,,,,,,
刺客,3235.500,340.000,172.667,0.0,87.333,50.0,0.0,0.0,48.167,19.667
坦克,3353.909,307.727,163.591,0.0,109.227,50.0,0.0,0.0,53.455,11.000
射手,3140.700,416.000,168.600,0.0,88.200,50.0,0.0,0.0,40.000,19.000
战士,3195.867,318.667,167.400,0.0,95.667,50.0,0.0,0.0,49.000,11.333
法师,3102.750,487.500,164.500,0.0,91.438,50.0,0.0,0.0,43.875,17.500
辅助,3098.000,470.000,159.000,0.0,94.500,50.0,0.0,0.0,40.000,17.000

In [11]:
#查看分组后的重复数
#统计近战和远战英雄的数量
hero.groupby(['攻击范围']).count()['最大生命']

攻击范围
近程    38
远程    33
Name: 最大生命, dtype: int64

In [12]:
#查看每一种英雄生命值回复平均值排名
hero.groupby(['英雄类型'])['生命回复'].mean().sort_values(ascending = False).round(3)

英雄类型
坦克    53.455
战士    49.000
刺客    48.167
法师    43.875
射手    40.000
辅助    40.000
Name: 生命回复, dtype: float64

In [13]:
#布尔索引查询某一行
hero[hero['英雄名称'] == '孙悟空']

,英雄类型,英雄名称,最大生命,最大法力,物理攻击,法术攻击,物理防御,物理减伤率,法术防御,法术减伤率,...,攻速加成,暴击几率,暴击效果,物理吸血,法术吸血,冷却缩减,攻击范围,韧性,生命回复,法力回复
26,战士,孙悟空,3305,430,167,0,98,14%,50,7.6%,...,0,20,200%,0,0,0%,近程,0,50,15

In [14]:
hero[hero['法术攻击'] == 0]

,英雄类型,英雄名称,最大生命,最大法力,物理攻击,法术攻击,物理防御,物理减伤率,法术防御,法术减伤率,...,攻速加成,暴击几率,暴击效果,物理吸血,法术吸血,冷却缩减,攻击范围,韧性,生命回复,法力回复
0,坦克,苏烈,3369,0,171,0,93,13.4%,50,7.6%,...,0,0,200%,0,0,0%,近程,0,56,0
1,坦克,芈月,3105,100,152,0,88,12.7%,50,7.6%,...,0,0,200%,0,0,0%,远程,0,44,0
2,坦克,墨子,3083,420,181,0,102,14.5%,50,7.6%,...,0,0,200%,0,0,0%,近程,0,51,15
3,坦克,白起,3510,420,158,0,120,16.6%,50,7.6%,...,0,0,200%,0,0,0%,近程,0,58,14
4,坦克,庄周,3311,420,170,0,150,20%,50,7.6%,...,0,0,200%,0,0,0%,近程,0,55,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,射手,艾琳,3182,440,161,0,86,12.5%,50,7.6%,...,0,0,200%,0,0,0%,远程,0,41,16
67,坦克,太乙真人,3443,420,154,0,94,13.5%,50,0%,...,0,0,0%,0,0,0%,近程,0,49,15
68,辅助,大乔,2958,470,159,0,93,13.4%,50,7.6%,...,0,0,200%,0,0,0%,远程,0,42,17
69,法师,孙膑,3208,470,176,0,98,14.1%,50,7.6%,...,0,0,200%,0,0,0%,远程,0,45,17
70,辅助,蔡文姬,3238,470,159,0,96,13.7%,50,7.6%,...,0,0,200%,0,0,0%,远程,0,38,17

In [15]:
#选取两组人，进行数据优劣比较
num_1 = hero[hero.英雄名称.isin(['鲁班七号','武则天','程咬金','李白','太乙真人'])]
num_2 = hero[hero.英雄名称.isin(['孙尚香','诸葛亮','钟无艳','孙悟空','孙膑'])]
num_1

,英雄类型,英雄名称,最大生命,最大法力,物理攻击,法术攻击,物理防御,物理减伤率,法术防御,法术减伤率,...,攻速加成,暴击几率,暴击效果,物理吸血,法术吸血,冷却缩减,攻击范围,韧性,生命回复,法力回复
16,坦克,程咬金,3437,0,161,0,125,17.2%,50,7.6%,...,0,0,200%,0,0,0%,远程,0,57,0
24,战士,李白,2968,450,169,0,98,14%,50,7.6%,...,0,0,200%,0,0,0%,近程,0,49,16
46,法师,武则天,2860,490,173,0,95,13.6%,50,7.6%,...,0,0,200%,0,0,0%,远程,0,40,18
64,射手,鲁班七号,3401,440,174,0,88,12.7%,50,7.6%,...,0,0,200%,0,0,0%,远程,0,42,15
67,坦克,太乙真人,3443,420,154,0,94,13.5%,50,0%,...,0,0,0%,0,0,0%,近程,0,49,15

In [16]:
num_2

,英雄类型,英雄名称,最大生命,最大法力,物理攻击,法术攻击,物理防御,物理减伤率,法术防御,法术减伤率,...,攻速加成,暴击几率,暴击效果,物理吸血,法术吸血,冷却缩减,攻击范围,韧性,生命回复,法力回复
14,坦克,钟无艳,3150,430,164,0,100,14.2%,50,7.6%,...,0,0,200%,0,0,0%,近程,0,48,15
26,战士,孙悟空,3305,430,167,0,98,14%,50,7.6%,...,0,20,200%,0,0,0%,近程,0,50,15
36,法师,诸葛亮,3135,490,156,0,87,12.6%,50,7.6%,...,0,0,0%,0,0,0%,远程,0,44,18
63,射手,孙尚香,3235,440,172,0,89,12.9%,50,7.6%,...,0,0,200%,0,0,0%,远程,0,40,15
69,法师,孙膑,3208,470,176,0,98,14.1%,50,7.6%,...,0,0,200%,0,0,0%,远程,0,45,17

In [17]:
num_1.mean(numeric_only = True) - num_2.mean(numeric_only = True)

最大生命      15.2
最大法力     -92.0
物理攻击      -0.8
法术攻击       0.0
物理防御       5.6
法术防御       0.0
物理护甲穿透     0.0
法术护甲穿透     0.0
生命回复       2.0
法力回复      -3.2
dtype: float64